const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');
const ts=require(require.resolve('typescript',{paths:[path.resolve(__dirname,'../../app')]}));
const source=fs.readFileSync(path.join(__dirname,'office-script.ts'),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS},reportDiagnostics:true});
assert.deepEqual(compiled.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error),[]);
const context=vm.createContext({ExcelScript:{SpecialCellType:{formulas:'formulas'}}});vm.runInContext(compiled.outputText+'\nglobalThis.api={SPECS,canonical,sha256,rowDigest,machineHeaders,validateEnvelope,planTable,validateReferences,verifyPostread,calculatedFormula,checkManagedFormulas,safeLiteral,writeRow,findReceipt,main};',context);const api=context.api;
const plain=v=>JSON.parse(JSON.stringify(v));
function change(specIndex,key,extra={}){const spec=api.SPECS[specIndex],values=Object.fromEntries(api.machineHeaders(spec).map(h=>[h,'']));values[spec.key]=key;values[spec.displayKey]=key;if(specIndex===1||specIndex===2)values['Action ID']='A01';return {key,expectedMachineSha256:null,values:{...values,...extra},links:Object.fromEntries(spec.linkColumns.map(h=>[h,'']))};}
function image(specIndex,changes){const spec=api.SPECS[specIndex];return {spec,rows:changes.map(row=>({key:row.key,values:{...row.values},links:{...row.links},human:Object.fromEntries(spec.human.map(h=>[h,h==='Status'?'Investigating':h==='Owner'?'@Test owner':h==='Due (Pacific)'?46200:'- Preserve my note'])),formulas:Object.fromEntries(spec.calculated.map(h=>[h,api.calculatedFormula(spec,h)]))}))};}
function envelope(changes={actions:[change(0,'A01')],instances:[],emails:[],dailyRows:[]}){const b={schemaVersion:1,batchId:'batch-1',workbookKey:'synthetic-workbook',expectedRevision:0,generatedAt:'2026-10-01T22:00:00Z',changes};return {...b,payloadSha256:crypto.createHash('sha256').update(api.canonical(b)).digest('hex')};}
function rehash(batch){const b={...batch};delete b.payloadSha256;return {...b,payloadSha256:api.sha256(api.canonical(b))};}

test('SHA-256 agrees with Node for UTF-8, emoji, lone surrogates and multiple blocks',()=>{for(const text of ['', 'abc', 'a'.repeat(1000), 'Arianna — test 🏃', '\ud800'])assert.equal(api.sha256(text),crypto.createHash('sha256').update(text).digest('hex'));});
test('canonical payload order is stable and data tampering is rejected',()=>{const b=envelope();api.validateEnvelope(b);assert.equal(api.canonical({b:1,a:2}),api.canonical({a:2,b:1}));b.changes.actions[0].values.Problem='changed';assert.throws(()=>api.validateEnvelope(b),/digest/);});
test('cannot send human or calculated columns',()=>{for(const field of ['Status','Owner','Due (Pacific)','Fix notes','Records']){const b=envelope();b.changes.actions[0].values[field]='overwritten';assert.throws(()=>api.validateEnvelope(rehash(b)),/schema/);}});
test('duplicate payload source keys and mixed unknown columns fail',()=>{const b=envelope();b.changes.actions.push(plain(b.changes.actions[0]));assert.throws(()=>api.validateEnvelope(rehash(b)),/duplicate/);const c=envelope();c.changes.actions[0].links.Unexpected='https://example.test';assert.throws(()=>api.validateEnvelope(rehash(c)),/Link schema/);});
test('reject oversized batches before any write',()=>{const b=envelope({actions:Array.from({length:151},(_,i)=>change(0,'A'+i)),instances:[],emails:[],dailyRows:[]});assert.throws(()=>api.validateEnvelope(b),/150/);});
test('zero-change material replay can be verified without inventing row changes',()=>{api.validateEnvelope(envelope({actions:[],instances:[],emails:[],dailyRows:[]}));});
test('native Excel precision is validated before any workbook access',()=>{const raw=46296.00648148148,rounded=Number(raw.toPrecision(15)),row=change(3,'daily-precision',{'Job created (Pacific)':raw});assert.notEqual(raw,rounded);const invalid=envelope({actions:[],instances:[],emails:[],dailyRows:[row]});assert.throws(()=>api.main({},JSON.stringify(invalid)),/Excel precision/);row.values['Job created (Pacific)']=rounded;api.validateEnvelope(envelope({actions:[],instances:[],emails:[],dailyRows:[row]}));});
test('stable raw IDs and formula-looking source text remain in digest unchanged',()=>{const c=change(2,'+raw-outlook-id',{'Original subject':'=literal subject'});const b=envelope({actions:[],instances:[],emails:[c],dailyRows:[]});api.validateEnvelope(b);assert.equal(c.key,'+raw-outlook-id');assert.equal(c.values['Outlook message ID'],c.key);});
// This narrow model covers coercions confirmed in native Excel acceptance. It
// deliberately differs from a pass-through setValues mock, which missed dates.
function excelCoerce(value){if(typeof value==='number')return Number(value.toPrecision(15));if(typeof value!=='string'||value==='')return value;if(value[0]==="'")return value.slice(1);if(/^\d{4}-\d{2}-\d{2}$/.test(value))return (Date.parse(value+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000;if(/^[+-]?\d+(\.\d+)?$/.test(value))return Number(value);if(/^[=+\-@]/.test(value))return 'FORMULA:'+value;return value;}
test('native literal escaping preserves ISO dates, numeric IDs, long IDs and original apostrophes',()=>{const samples=['2026-10-01','00123','=1+1',"'quoted",'hello','','12345678901234567890',"''two",'+12','-7','@name','1.25'];assert.equal(excelCoerce('2026-10-01'),46296);assert.equal(excelCoerce('00123'),123);assert.equal(excelCoerce("'quoted"),'quoted');for(const value of samples)assert.equal(excelCoerce(api.safeLiteral(value)),value);for(const value of [0,46296.625,false,true])assert.equal(api.safeLiteral(value),value);});
function coercingDailyBook(initial=[],{beforeLiveRead=()=>{},formulaColumn=null}={}){const spec=api.SPECS[3],rows=plain(initial);const sheet={getName:()=>spec.sheet,getProtection:()=>({getProtected:()=>false})};const range=()=>({getValues:()=>{throw new Error('Row lookup must read only the current key column');},getRow:row=>({getValues:()=>{beforeLiveRead(rows);return [rows[row].slice()];},getColumnIndex:()=>spec.column,getSpecialCells:()=>formulaColumn===null?undefined:{getAreas:()=>[{getColumnIndex:()=>spec.column+formulaColumn,getColumnCount:()=>1}]}}),getCell:(row,col)=>({getResizedRange:(_r,width)=>({setValues:values=>{for(let c=0;c<=width;c++)rows[row][col+c]=excelCoerce(values[0][c]);}})})});const table={getWorksheet:()=>sheet,getHeaderRowRange:()=>({getValues:()=>[spec.headers],getRowIndex:()=>spec.row,getColumnIndex:()=>spec.column}),getShowTotals:()=>false,getRangeBetweenHeaderAndTotal:range,getColumnByName:name=>{assert.equal(name,spec.key);return {getRangeBetweenHeaderAndTotal:()=>({getValues:()=>rows.map(row=>[row[4]])})};},addRows:(_index,values)=>rows.push(...values.map(row=>row.map(excelCoerce)))};return {book:{getTable:()=>table},rows};}
test('native row append protects a numeric-looking source key and date text before key lookup',()=>{const row=change(3,'00123',{'Reporting day':'2026-10-01','Job created (Pacific)':46296.625,Delivery:"'quoted",'Provider code':'=literal'}),{book,rows}=coercingDailyBook();api.writeRow(book,{spec:api.SPECS[3]},{change:row,existed:false,alreadyApplied:false});assert.deepEqual(plain(rows),[['2026-10-01',46296.625,"'quoted",'=literal','00123']]);});
test('normalized fractional dates retain exact hashes through native numeric coercion',()=>{assert.equal(excelCoerce(46296.00648148148),46296.0064814815);const row=change(3,'daily-numeric',{'Reporting day':'2026-10-01','Job created (Pacific)':46296.0064814815}),{book,rows}=coercingDailyBook();api.writeRow(book,{spec:api.SPECS[3]},{change:row,existed:false,alreadyApplied:false});const actual={values:Object.fromEntries(api.SPECS[3].headers.map((h,i)=>[h,rows[0][i]])),links:{}};assert.equal(api.rowDigest(actual),api.rowDigest(row));});
test('native existing-row update preserves text while retaining typed numeric dates',()=>{const previous=change(3,'00123',{'Reporting day':'2026-10-01','Job created (Pacific)':46296.625,Delivery:'Pending'}),row=change(3,'00123',{'Reporting day':'2026-10-02','Job created (Pacific)':46297.625,Delivery:'12345678901234567890','Provider code':"''two"}),{book,rows}=coercingDailyBook([['2026-10-01',46296.625,'Pending','','00123']]);row.expectedMachineSha256=api.rowDigest(previous);api.writeRow(book,{spec:api.SPECS[3],human:{'00123':{}}},{change:row,existed:true,alreadyApplied:false});assert.deepEqual(rows,[['2026-10-02',46297.625,'12345678901234567890',"''two",'00123']]);});
test('native row update refuses a machine edit after planning without overwriting it',()=>{const previous=change(3,'daily-one',{'Reporting day':'Reviewed day','Job created (Pacific)':46296.625,Delivery:'pending'}),next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.values.Delivery='delivered';const {book,rows}=coercingDailyBook([['Reviewed day',46296.625,'pending','','daily-one']],{beforeLiveRead:rows=>{rows[0][2]='human correction';}});assert.throws(()=>api.writeRow(book,{spec:api.SPECS[3],human:{'daily-one':{}}},{change:next,existed:true,alreadyApplied:false}),/changed before write/);assert.equal(rows[0][2],'human correction');});
test('native row update refuses a sort between key lookup and row read',()=>{const previous=change(3,'daily-one',{'Reporting day':'Reviewed day','Job created (Pacific)':46296.625,Delivery:'pending'}),next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.values.Delivery='delivered';const {book,rows}=coercingDailyBook([['Reviewed day',46296.625,'pending','','daily-one'],['Other day',46295,'pending','','daily-two']],{beforeLiveRead:rows=>rows.reverse()});assert.throws(()=>api.writeRow(book,{spec:api.SPECS[3],human:{'daily-one':{}}},{change:next,existed:true,alreadyApplied:false}),/moved during write/);assert.ok(rows.every(row=>row[2]==='pending'));});
test('native row update refuses a newly inserted formula even if its value matches',()=>{const previous=change(3,'daily-one',{'Reporting day':'Reviewed day','Job created (Pacific)':46296.625,Delivery:'pending'}),next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.values.Delivery='delivered';const {book,rows}=coercingDailyBook([['Reviewed day',46296.625,'pending','','daily-one']],{formulaColumn:1});assert.throws(()=>api.writeRow(book,{spec:api.SPECS[3],human:{'daily-one':{}}},{change:next,existed:true,alreadyApplied:false}),/formula appeared/);assert.equal(rows[0][2],'pending');});
test('native action write leaves a late owner edit untouched and performs no machine writes',()=>{const previous=change(0,'A01',{Problem:'Reviewed problem'}),before=image(0,[previous]),next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.values.Problem='New diagnosis';const spec=api.SPECS[0],human=plain(before.rows[0].human),cells=spec.headers.map(h=>previous.values[h]??human[h]??1);cells[10]='New teammate owner';let writes=0;const rowRange={getValues:()=>[cells],getSpecialCells:()=>undefined,getCell:()=>({getHyperlink:()=>undefined})};const sheet={getName:()=>spec.sheet,getProtection:()=>({getProtected:()=>false})};const table={getWorksheet:()=>sheet,getHeaderRowRange:()=>({getValues:()=>[spec.headers],getRowIndex:()=>spec.row,getColumnIndex:()=>spec.column}),getShowTotals:()=>false,getColumnByName:()=>({getRangeBetweenHeaderAndTotal:()=>({getValues:()=>[['A01']]})}),getRangeBetweenHeaderAndTotal:()=>({getRow:()=>rowRange,getCell:()=>({getResizedRange:()=>({setValues:()=>writes++})})})};assert.throws(()=>api.writeRow({getTable:()=>table},{spec,human:{A01:human}},{change:next,existed:true,alreadyApplied:false}),/Human fields changed before write/);assert.equal(cells[10],'New teammate owner');assert.equal(cells[2],'Reviewed problem');assert.equal(writes,0);});
test('native receipt matching requires preserving a numeric-looking batch ID as text',()=>{const batch=rehash({...envelope(),batchId:'00123'}),receipt={schemaVersion:1,batchId:batch.batchId,workbookKey:batch.workbookKey,payloadSha256:batch.payloadSha256,verified:true,revision:1,applied:{actions:['A01'],instances:[],emails:[],dailyRows:[]},counts:{actions:1,instances:0,emails:0,dailyRows:0}},raw=[batch.batchId,batch.payloadSha256,1,JSON.stringify(receipt)];let rows=[raw.map(excelCoerce)];const book={getTable:()=>({getWorksheet:()=>({getName:()=>'_TrackerSync'}),getHeaderRowRange:()=>({getValues:()=>[['Batch ID','Payload SHA256','Revision','Receipt JSON']]}),getRowCount:()=>1,getRangeBetweenHeaderAndTotal:()=>({getValues:()=>rows})})};assert.equal(api.findReceipt(book,batch),undefined);rows=[raw.map(v=>excelCoerce(api.safeLiteral(v)))];assert.deepEqual(plain(api.findReceipt(book,batch)),receipt);});
test('sorted rows preserve human fields by source key',()=>{const a=change(0,'A01'),b=change(0,'A02');const before=image(0,[b,a]),next=plain(a);next.expectedMachineSha256=api.rowDigest(before.rows[1]);next.values.Problem='A new diagnosis';const p=api.planTable(before,[next],false);assert.equal(p.updates[0].change.key,'A01');assert.equal(p.human.A01.Owner,'@Test owner');assert.equal(p.human.A01['Fix notes'],'- Preserve my note');assert.deepEqual(plain(p.existingKeys),['A02','A01']);});
test('reject duplicate existing source/display IDs and missing expected rows',()=>{const a=change(0,'A01');assert.throws(()=>api.planTable(image(0,[a,a]),[],false),/Duplicate/);const b=change(1,'source-two',{Instance:'shared'}),c=change(1,'source-three',{Instance:'shared'});assert.throws(()=>api.planTable(image(1,[b,c]),[],false),/Duplicate/);const next=change(0,'A02');next.expectedMachineSha256='a'.repeat(64);assert.throws(()=>api.planTable(image(0,[a]),[next],false),/Missing/);});
test('manual machine-cell/hyperlink conflicts are not overwritten',()=>{const a=change(0,'A01'),before=image(0,[a]),next=plain(a);next.expectedMachineSha256=api.rowDigest(before.rows[0]);before.rows[0].values.Problem='manual edit';assert.throws(()=>api.planTable(before,[next],false),/conflict/);before.rows[0].values.Problem='';before.rows[0].links['Code / evidence']='https://example.test/changed';assert.throws(()=>api.planTable(before,[next],false),/conflict/);});
test('source URL replacement/removal stops in planning while blank enrichment remains allowed',()=>{const previous=change(1,'linked-source',{'Private issue':'Open issue'});previous.links['Private issue']='https://example.test/original';for(const url of ['','https://example.test/replaced']){const next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.links['Private issue']=url;assert.throws(()=>api.planTable(image(1,[previous]),[next],false),/URL replacement\/removal/);}const blank=change(1,'unmatched-source'),enriched=plain(blank);enriched.expectedMachineSha256=api.rowDigest(blank);enriched.values['Private issue']='Open issue';enriched.links['Private issue']='https://example.test/exact';assert.equal(api.planTable(image(1,[blank]),[enriched],false).updates.length,1);});
test('unchanged native range hyperlinks are not reset or cleared during a machine update',()=>{const previous=change(1,'source-with-range-link',{'Private issue':'Open issue'});previous.links['Private issue']='https://example.test/shared-range';const next=plain(previous);next.expectedMachineSha256=api.rowDigest(previous);next.values['Error / actual evidence']='Updated evidence';const spec=api.SPECS[1],cells=spec.headers.map(h=>previous.values[h]??''),sheet={getName:()=>spec.sheet,getProtection:()=>({getProtected:()=>false})};const getCell=(r,c)=>({getHyperlink:()=>({address:previous.links[spec.headers[c]]||''}),setHyperlink:()=>{throw new Error('Resetting one cell would overlap a range link');},clear:()=>{throw new Error('Clearing one cell would erase neighbor links');},getResizedRange:(_r,width)=>({setValues:values=>{for(let i=0;i<=width;i++)cells[c+i]=excelCoerce(values[0][i]);}})});const row={getValues:()=>[cells.slice()],getSpecialCells:()=>undefined,getCell};const table={getWorksheet:()=>sheet,getHeaderRowRange:()=>({getValues:()=>[spec.headers],getRowIndex:()=>spec.row,getColumnIndex:()=>spec.column}),getShowTotals:()=>false,getColumnByName:()=>({getRangeBetweenHeaderAndTotal:()=>({getValues:()=>[[previous.key]]})}),getRangeBetweenHeaderAndTotal:()=>({getRow:()=>row,getCell})};api.writeRow({getTable:()=>table},{spec,human:{[previous.key]:{}}},{change:next,existed:true,alreadyApplied:false});assert.equal(cells[5],'Updated evidence');assert.equal(cells[17],'Open issue');});
test('exact pending retry recognizes completed row and rejects partial/conflicting row',()=>{const a=change(0,'A01'),next=plain(a);next.expectedMachineSha256=api.rowDigest(a);next.values.Problem='updated';const current=image(0,[next]);assert.equal(api.planTable(current,[next],true).updates[0].alreadyApplied,true);assert.throws(()=>api.planTable(current,[next],false),/conflict/);current.rows[0].values.Problem='partial';assert.throws(()=>api.planTable(current,[next],true),/conflict/);});
test('recurrence on a manually resolved action requires machine flag but never reopens it',()=>{const a=change(0,'A01'),i=change(1,'event-one'),images=[image(0,[a]),image(1,[]),image(2,[]),image(3,[])];images[0].rows[0].human.Status='Resolved';const plans=images.map((img,n)=>api.planTable(img,n===1?[i]:[],false));assert.throws(()=>api.validateReferences(images,plans),/recurrence/);const next=plain(a);next.expectedMachineSha256=api.rowDigest(images[0].rows[0]);next.values['Observed evidence / limits']='Recurrence recorded: event-one';plans[0]=api.planTable(images[0],[next],false);api.validateReferences(images,plans);assert.equal(images[0].rows[0].human.Status,'Resolved');});
test('unresolved references reject a batch',()=>{const images=[image(0,[]),image(1,[]),image(2,[]),image(3,[])],plans=images.map((img,n)=>api.planTable(img,n===1?[change(1,'missing-action-event')]:[],false));assert.throws(()=>api.validateReferences(images,plans),/Unknown Action/);});
test('postread validates full source retention, human edits, source URLs and new daily history',()=>{const a=change(0,'A01'),d=change(3,'daily-one'),next=change(3,'daily-two');const before=[image(0,[a]),image(1,[]),image(2,[]),image(3,[d])],plans=before.map((img,n)=>api.planTable(img,n===3?[next]:[],false));const after=plain(before);after[3].rows.push(image(3,[next]).rows[0]);api.verifyPostread(before,after,plans);const lost=plain(after);lost[3].rows.shift();assert.throws(()=>api.verifyPostread(before,lost,plans),/count|disappeared/);const human=plain(after);human[0].rows[0].human.Owner='concurrent editor';assert.throws(()=>api.verifyPostread(before,human,plans),/Human/);});
test('postread refuses incorrect values even when provided digests match expected payload',()=>{const a=change(0,'A01'),next=change(1,'event-one'),before=[image(0,[a]),image(1,[]),image(2,[]),image(3,[])],plans=before.map((img,n)=>api.planTable(img,n===1?[next]:[],false)),after=plain(before);after[1].rows.push(image(1,[next]).rows[0]);after[1].rows[0].values['Error / actual evidence']='wrong';assert.throws(()=>api.verifyPostread(before,after,plans),/Postread/);});
test('stored exact-batch replay returns original verified receipt without table writes',()=>{const batch=envelope(),receipt={schemaVersion:1,batchId:batch.batchId,workbookKey:batch.workbookKey,payloadSha256:batch.payloadSha256,verified:true,revision:1,applied:{actions:['A01'],instances:[],emails:[],dailyRows:[]},counts:{actions:1,instances:0,emails:0,dailyRows:0}};const state={schemaVersion:1,workbookKey:batch.workbookKey,revision:1,mode:'ready',pendingBatchId:'',initialCounts:receipt.counts};const book={getWorksheet:()=>({getRange:()=>({getValue:()=>JSON.stringify(state)})}),getTable:()=>({getWorksheet:()=>({getName:()=>'_TrackerSync'}),getHeaderRowRange:()=>({getValues:()=>[['Batch ID','Payload SHA256','Revision','Receipt JSON']]}),getRowCount:()=>1,getRangeBetweenHeaderAndTotal:()=>({getValues:()=>[[batch.batchId,batch.payloadSha256,1,JSON.stringify(receipt)]]})})};assert.deepEqual(JSON.parse(api.main(book,JSON.stringify(batch))),receipt);});
test('stale revision and changed payload under reused batch ID fail before source writes',()=>{const b=envelope();const state={schemaVersion:1,workbookKey:b.workbookKey,revision:2,mode:'ready',pendingBatchId:''};const book={getWorksheet:()=>({getRange:()=>({getValue:()=>JSON.stringify(state)})}),getTable:()=>({getWorksheet:()=>({getName:()=>'_TrackerSync'}),getHeaderRowRange:()=>({getValues:()=>[['Batch ID','Payload SHA256','Revision','Receipt JSON']]}),getRowCount:()=>0})};assert.throws(()=>api.main(book,JSON.stringify(b)),/Stale/);});
test('pending recovery cannot erase a custom formula in an existing calculated cell',()=>{const a=change(0,'A01'),images=[image(0,[a])];images[0].rows[0].formulas.Records='=999';assert.throws(()=>api.checkManagedFormulas(images,{actions:[{...a,expectedMachineSha256:api.rowDigest(a)}],instances:[],emails:[],dailyRows:[]}),/Managed formula/);});

const bootstrapSource=source.slice(0,source.indexOf('function main(workbook:'))+fs.readFileSync(path.join(__dirname,'bootstrap-main.ts'),'utf8');
const bootstrapJs=ts.transpileModule(bootstrapSource,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS},reportDiagnostics:true});
assert.deepEqual(bootstrapJs.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error),[]);
const bootContext=vm.createContext({ExcelScript:{SpecialCellType:{formulas:'formulas'}}});vm.runInContext(bootstrapJs.outputText+'\nglobalThis.bootstrap=main;globalThis.verifyBootstrapPreservation=verifyBootstrapPreservation;',bootContext);
function bootstrapBook(){
  const images=[image(0,[change(0,'A01')]),image(1,[change(1,'existing-occurrence')]),image(2,[change(2,'existing-mail')])];
  const footer=[Array(24).fill(''),[...api.SPECS[3].headers,...Array(19).fill('')],['Report period',46200,'pending','429','daily-one',...Array(19).fill('')],Array(24).fill('')];
  const makeRange=(spec,rows)=>({getValues:()=>rows,getFormulas:()=>rows,getSpecialCells:()=>undefined,getRowIndex:()=>spec.row+1,getColumnIndex:()=>spec.column,getRowCount:()=>rows.length,getCell:()=>({getHyperlink:()=>undefined})});
  const sheets={Actions:{getName:()=>'Actions',getProtection:()=>({getProtected:()=>false})},Instances:{getName:()=>'Instances',getProtection:()=>({getProtected:()=>false}),getRange:()=>({getValues:()=>footer,getSpecialCells:()=>undefined,getRowIndex:()=>29})},Emails:{getName:()=>'Emails',getProtection:()=>({getProtected:()=>false})}};
  return {book:{getWorksheets:()=>Object.values(sheets),getWorksheet:name=>sheets[name],getTable:name=>{const img=images.find(i=>i.spec.table===name);if(!img)return undefined;const rows=img.rows.map(row=>img.spec.headers.map(h=>row.values[h]??row.human[h]??row.formulas[h]??''));return {getWorksheet:()=>sheets[img.spec.sheet],getHeaderRowRange:()=>({getValues:()=>[img.spec.headers],getRowIndex:()=>img.spec.row,getColumnIndex:()=>img.spec.column}),getShowTotals:()=>false,getRowCount:()=>rows.length,getRangeBetweenHeaderAndTotal:()=>makeRange(img.spec,rows),getRange:()=>({getRowIndex:()=>img.spec.row,getRowCount:()=>rows.length+1})};}},footer};
}
test('read-only bootstrap exports exact known IDs and machine hashes without inferring groups',()=>{const {book}=bootstrapBook();const result=JSON.parse(bootContext.bootstrap(book,JSON.stringify({mode:'inspect',workbookKey:'test',expectedSourceSha256:'',footerAddress:'A30:X33',expectedFooter:[],dailyRows:[]})));assert.equal(result.groupingMapVerified,false);assert.equal(result.seed[0].rows[0].key,'A01');assert.equal(result.seed[1].rows[0].key,'existing-occurrence');assert.equal(result.seed[2].rows[0].key,'existing-mail');assert.match(result.seed[0].rows[0].machineSha256,/^[a-f0-9]{64}$/);});
test('bootstrap refuses a stale reviewed source before changing any native cell',()=>{const {book,footer}=bootstrapBook();assert.throws(()=>bootContext.bootstrap(book,JSON.stringify({mode:'initialize',workbookKey:'test',expectedSourceSha256:'0'.repeat(64),footerAddress:'A30:X33',expectedFooter:footer,dailyRows:[]})),/changed since/);});
test('bootstrap final postread preserves source links, exact order and human notes',()=>{const before=[image(0,[change(0,'A02'),change(0,'A01')]),image(1,[change(1,'source-one')]),image(2,[change(2,'mail-one')])];bootContext.verifyBootstrapPreservation(before,plain(before));const human=plain(before);human[0].rows[1].human['Fix notes']='concurrent note';assert.throws(()=>bootContext.verifyBootstrapPreservation(before,human),/Human fields/);const link=plain(before);link[1].rows[0].links['Private issue']='https://example.test/changed';assert.throws(()=>bootContext.verifyBootstrapPreservation(before,link),/values\/links/);const sorted=plain(before);sorted[0].rows.reverse();assert.throws(()=>bootContext.verifyBootstrapPreservation(before,sorted),/order\/count/);});

const {convertBootstrapSeed}=require('./convert-bootstrap-seed.cjs');
function exportedSeed(){const groups=[['actions',change(0,'A01')],['instances',change(1,'raw-occurrence',{Instance:'EV-003'})],['emails',change(2,'raw-mail',{Email:'EM-005','Linked instance':'EV-003'})],['dailyRows',change(3,'daily-reference',{'Reporting day':'Reviewed reporting window'})]];const sourceSha256='a'.repeat(64);return {snapshot:{initialized:true,revision:0,workbookKey:'test',sourceSha256,counts:{actions:1,instances:1,emails:1,dailyRows:1},seed:groups.map(([group,row])=>({group,rows:[{key:row.key,values:row.values,links:row.links,machineSha256:api.rowDigest(row)}]}))},review:{schemaVersion:1,reviewed:true,workbookKey:'test',mailbox:'synthetic@example.test',sourceSha256,actionMappings:{'reviewed-signature':'A01'}}};}
test('offline seed conversion preserves raw IDs, existing display IDs, exact mail joins and daily period',()=>{const {snapshot,review}=exportedSeed(),result=convertBootstrapSeed(snapshot,review);assert.equal(result.settings.enabled,false);assert.equal(result.settings.seedVerified,false);assert.deepEqual(result.seedMetadata.counters,{action:1,instance:3,email:5});assert.deepEqual(result.seedMetadata.counts,{actions:1,instances:1,emails:1,dailyRows:1});assert.equal(result.rowDocuments.find(row=>row.data.group==='emails').data.value.eventRef,'raw-occurrence');assert.equal(result.rowDocuments.find(row=>row.data.group==='dailyRows').data.value.values['Reporting day'],'Reviewed reporting window');assert.equal(result.seedMetadata.actionMappings['reviewed-signature'],'A01');});
test('offline seed conversion cannot invent missing group mappings or ignore changed native hashes',()=>{const {snapshot,review}=exportedSeed();review.actionMappings.bad='A99';assert.throws(()=>convertBootstrapSeed(snapshot,review),/missing Action/);delete review.actionMappings.bad;snapshot.seed[0].rows[0].values.Problem='altered';assert.throws(()=>convertBootstrapSeed(snapshot,review),/hash mismatch/);});
test('real backend normalizer and sealed bridge payload match native writer schema and hash contract',()=>{const {normalizeIssueTracker}=require('../../functions/issue-tracker-normalize'),{sealBatch}=require('../../functions/issue-tracker-bridge-model');const id='a'.repeat(64),normalized=normalizeIssueTracker({occurrences:[{id,issueId:'b'.repeat(64),message:'Synthetic unknown failure',operation:'synthetic-test',receivedAtMillis:1790892000000}],outbox:[{id,type:'incident',issueId:'b'.repeat(64),status:'pending'}]});const batch=sealBatch({batchId:'synthetic-integration',workbookKey:'test',expectedRevision:0,generatedAt:'2026-10-01T22:00:00.000Z',changes:normalized.changes});api.validateEnvelope(batch);const images=api.SPECS.map((spec,i)=>image(i,[])),plans=images.map(img=>api.planTable(img,normalized.changes[img.spec.group],false));api.validateReferences(images,plans);assert.equal(plans[1].updates[0].change.key,id);});
