const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');
const ts=require(require.resolve('typescript',{paths:[path.resolve(__dirname,'../../app')]}));
const source=fs.readFileSync(path.join(__dirname,'office-script.ts'),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS},reportDiagnostics:true});
assert.deepEqual(compiled.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error),[]);
const context=vm.createContext({ExcelScript:{SpecialCellType:{formulas:'formulas'}}});vm.runInContext(compiled.outputText+'\nglobalThis.api={SPECS,canonical,sha256,rowDigest,machineHeaders,validateEnvelope,planTable,validateReferences,verifyPostread,calculatedFormula,checkManagedFormulas,main};',context);const api=context.api;
const plain=v=>JSON.parse(JSON.stringify(v));
function change(specIndex,key,extra={}){const spec=api.SPECS[specIndex],values=Object.fromEntries(api.machineHeaders(spec).map(h=>[h,'']));values[spec.key]=key;values[spec.displayKey]=key;if(specIndex===1||specIndex===2)values['Action ID']='A01';return {key,expectedMachineSha256:null,values:{...values,...extra},links:Object.fromEntries(spec.linkColumns.map(h=>[h,'']))};}
function image(specIndex,changes){const spec=api.SPECS[specIndex];return {spec,rows:changes.map(row=>({key:row.key,values:{...row.values},links:{...row.links},human:Object.fromEntries(spec.human.map(h=>[h,h==='Status'?'Investigating':h==='Owner'?'@Test owner':h==='Due (Pacific)'?46200:'- Preserve my note'])),formulas:Object.fromEntries(spec.calculated.map(h=>[h,api.calculatedFormula(spec,h)]))}))};}
function envelope(changes={actions:[change(0,'A01')],instances:[],emails:[],dailyRows:[]}){const b={schemaVersion:1,batchId:'batch-1',workbookKey:'synthetic-workbook',expectedRevision:0,generatedAt:'2026-10-01T22:00:00Z',changes};return {...b,payloadSha256:crypto.createHash('sha256').update(api.canonical(b)).digest('hex')};}
function rehash(batch){const b={...batch};delete b.payloadSha256;return {...b,payloadSha256:api.sha256(api.canonical(b))};}

test('SHA-256 agrees with Node for UTF-8, emoji, lone surrogates and multiple blocks',()=>{for(const text of ['', 'abc', 'a'.repeat(1000), 'Arianna — test 🏃', '\ud800'])assert.equal(api.sha256(text),crypto.createHash('sha256').update(text).digest('hex'));});
test('canonical payload order is stable and data tampering is rejected',()=>{const b=envelope();api.validateEnvelope(b);assert.equal(api.canonical({b:1,a:2}),api.canonical({a:2,b:1}));b.changes.actions[0].values.Problem='changed';assert.throws(()=>api.validateEnvelope(b),/digest/);});
test('cannot send human or calculated columns',()=>{for(const field of ['Status','Owner','Due (Pacific)','Fix notes','Records']){const b=envelope();b.changes.actions[0].values[field]='overwritten';assert.throws(()=>api.validateEnvelope(rehash(b)),/schema/);}});
test('duplicate payload source keys and mixed unknown columns fail',()=>{const b=envelope();b.changes.actions.push(plain(b.changes.actions[0]));assert.throws(()=>api.validateEnvelope(rehash(b)),/duplicate/);const c=envelope();c.changes.actions[0].links.Unexpected='https://example.test';assert.throws(()=>api.validateEnvelope(rehash(c)),/Link schema/);});
test('reject oversized batches before any write',()=>{const b=envelope({actions:Array.from({length:151},(_,i)=>change(0,'A'+i)),instances:[],emails:[],dailyRows:[]});assert.throws(()=>api.validateEnvelope(b),/150/);});
test('zero-change material replay can be verified without inventing row changes',()=>{api.validateEnvelope(envelope({actions:[],instances:[],emails:[],dailyRows:[]}));});
test('stable raw IDs and formula-looking source text remain in digest unchanged',()=>{const c=change(2,'+raw-outlook-id',{'Original subject':'=literal subject'});const b=envelope({actions:[],instances:[],emails:[c],dailyRows:[]});api.validateEnvelope(b);assert.equal(c.key,'+raw-outlook-id');assert.equal(c.values['Outlook message ID'],c.key);});
test('sorted rows preserve human fields by source key',()=>{const a=change(0,'A01'),b=change(0,'A02');const before=image(0,[b,a]),next=plain(a);next.expectedMachineSha256=api.rowDigest(before.rows[1]);next.values.Problem='A new diagnosis';const p=api.planTable(before,[next],false);assert.equal(p.updates[0].change.key,'A01');assert.equal(p.human.A01.Owner,'@Test owner');assert.equal(p.human.A01['Fix notes'],'- Preserve my note');assert.deepEqual(plain(p.existingKeys),['A02','A01']);});
test('reject duplicate existing source/display IDs and missing expected rows',()=>{const a=change(0,'A01');assert.throws(()=>api.planTable(image(0,[a,a]),[],false),/Duplicate/);const b=change(1,'source-two',{Instance:'shared'}),c=change(1,'source-three',{Instance:'shared'});assert.throws(()=>api.planTable(image(1,[b,c]),[],false),/Duplicate/);const next=change(0,'A02');next.expectedMachineSha256='a'.repeat(64);assert.throws(()=>api.planTable(image(0,[a]),[next],false),/Missing/);});
test('manual machine-cell/hyperlink conflicts are not overwritten',()=>{const a=change(0,'A01'),before=image(0,[a]),next=plain(a);next.expectedMachineSha256=api.rowDigest(before.rows[0]);before.rows[0].values.Problem='manual edit';assert.throws(()=>api.planTable(before,[next],false),/conflict/);before.rows[0].values.Problem='';before.rows[0].links['Code / evidence']='https://example.test/changed';assert.throws(()=>api.planTable(before,[next],false),/conflict/);});
test('exact pending retry recognizes completed row and rejects partial/conflicting row',()=>{const a=change(0,'A01'),next=plain(a);next.expectedMachineSha256=api.rowDigest(a);next.values.Problem='updated';const current=image(0,[next]);assert.equal(api.planTable(current,[next],true).updates[0].alreadyApplied,true);assert.throws(()=>api.planTable(current,[next],false),/conflict/);current.rows[0].values.Problem='partial';assert.throws(()=>api.planTable(current,[next],true),/conflict/);});
test('recurrence on a manually resolved action requires machine flag but never reopens it',()=>{const a=change(0,'A01'),i=change(1,'event-one'),images=[image(0,[a]),image(1,[]),image(2,[]),image(3,[])];images[0].rows[0].human.Status='Resolved';const plans=images.map((img,n)=>api.planTable(img,n===1?[i]:[],false));assert.throws(()=>api.validateReferences(images,plans),/recurrence/);const next=plain(a);next.expectedMachineSha256=api.rowDigest(images[0].rows[0]);next.values['Observed evidence / limits']='Recurrence recorded: event-one';plans[0]=api.planTable(images[0],[next],false);api.validateReferences(images,plans);assert.equal(images[0].rows[0].human.Status,'Resolved');});
test('unresolved references reject a batch',()=>{const images=[image(0,[]),image(1,[]),image(2,[]),image(3,[])],plans=images.map((img,n)=>api.planTable(img,n===1?[change(1,'missing-action-event')]:[],false));assert.throws(()=>api.validateReferences(images,plans),/Unknown Action/);});
test('postread validates full source retention, human edits, source URLs and new daily history',()=>{const a=change(0,'A01'),d=change(3,'daily-one'),next=change(3,'daily-two');const before=[image(0,[a]),image(1,[]),image(2,[]),image(3,[d])],plans=before.map((img,n)=>api.planTable(img,n===3?[next]:[],false));const after=plain(before);after[3].rows.push(image(3,[next]).rows[0]);api.verifyPostread(before,after,plans);const lost=plain(after);lost[3].rows.shift();assert.throws(()=>api.verifyPostread(before,lost,plans),/count|disappeared/);const human=plain(after);human[0].rows[0].human.Owner='concurrent editor';assert.throws(()=>api.verifyPostread(before,human,plans),/Human/);});
test('postread refuses incorrect values even when provided digests match expected payload',()=>{const a=change(0,'A01'),next=change(1,'event-one'),before=[image(0,[a]),image(1,[]),image(2,[]),image(3,[])],plans=before.map((img,n)=>api.planTable(img,n===1?[next]:[],false)),after=plain(before);after[1].rows.push(image(1,[next]).rows[0]);after[1].rows[0].values['Error / actual evidence']='wrong';assert.throws(()=>api.verifyPostread(before,after,plans),/Postread/);});
test('stored exact-batch replay returns original verified receipt without table writes',()=>{const batch=envelope(),receipt={schemaVersion:1,batchId:batch.batchId,workbookKey:batch.workbookKey,payloadSha256:batch.payloadSha256,verified:true,revision:1,applied:{actions:['A01'],instances:[],emails:[],dailyRows:[]},counts:{actions:1,instances:0,emails:0,dailyRows:0}};const state={schemaVersion:1,workbookKey:batch.workbookKey,revision:1,mode:'ready',pendingBatchId:'',initialCounts:receipt.counts};const book={getWorksheet:()=>({getRange:()=>({getValue:()=>JSON.stringify(state)})}),getTable:()=>({getWorksheet:()=>({getName:()=>'_TrackerSync'}),getHeaderRowRange:()=>({getValues:()=>[['Batch ID','Payload SHA256','Revision','Receipt JSON']]}),getRowCount:()=>1,getRangeBetweenHeaderAndTotal:()=>({getValues:()=>[[batch.batchId,batch.payloadSha256,1,JSON.stringify(receipt)]]})})};assert.deepEqual(JSON.parse(api.main(book,JSON.stringify(batch))),receipt);});
test('stale revision and changed payload under reused batch ID fail before source writes',()=>{const b=envelope();const state={schemaVersion:1,workbookKey:b.workbookKey,revision:2,mode:'ready',pendingBatchId:''};const book={getWorksheet:()=>({getRange:()=>({getValue:()=>JSON.stringify(state)})}),getTable:()=>({getWorksheet:()=>({getName:()=>'_TrackerSync'}),getHeaderRowRange:()=>({getValues:()=>[['Batch ID','Payload SHA256','Revision','Receipt JSON']]}),getRowCount:()=>0})};assert.throws(()=>api.main(book,JSON.stringify(b)),/Stale/);});
test('pending recovery cannot erase a custom formula in an existing calculated cell',()=>{const a=change(0,'A01'),images=[image(0,[a])];images[0].rows[0].formulas.Records='=999';assert.throws(()=>api.checkManagedFormulas(images,{actions:[{...a,expectedMachineSha256:api.rowDigest(a)}],instances:[],emails:[],dailyRows:[]}),/Managed formula/);});

const bootstrapSource=source.slice(0,source.indexOf('function main(workbook:'))+fs.readFileSync(path.join(__dirname,'bootstrap-main.ts'),'utf8');
const bootstrapJs=ts.transpileModule(bootstrapSource,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS},reportDiagnostics:true});
assert.deepEqual(bootstrapJs.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error),[]);
const bootContext=vm.createContext({ExcelScript:{SpecialCellType:{formulas:'formulas'}}});vm.runInContext(bootstrapJs.outputText+'\nglobalThis.bootstrap=main;',bootContext);
function bootstrapBook(){
  const images=[image(0,[change(0,'A01')]),image(1,[change(1,'existing-occurrence')]),image(2,[change(2,'existing-mail')])];
  const footer=[Array(24).fill(''),[...api.SPECS[3].headers,...Array(19).fill('')],['Report period',46200,'pending','429','daily-one',...Array(19).fill('')],Array(24).fill('')];
  const makeRange=(spec,rows)=>({getValues:()=>rows,getFormulas:()=>rows,getSpecialCells:()=>undefined,getRowIndex:()=>spec.row+1,getColumnIndex:()=>spec.column,getRowCount:()=>rows.length,getCell:()=>({getHyperlink:()=>undefined})});
  const sheets={Actions:{getName:()=>'Actions',getProtection:()=>({getProtected:()=>false})},Instances:{getName:()=>'Instances',getProtection:()=>({getProtected:()=>false}),getRange:()=>({getValues:()=>footer,getSpecialCells:()=>undefined,getRowIndex:()=>29})},Emails:{getName:()=>'Emails',getProtection:()=>({getProtected:()=>false})}};
  return {book:{getWorksheets:()=>Object.values(sheets),getWorksheet:name=>sheets[name],getTable:name=>{const img=images.find(i=>i.spec.table===name);if(!img)return undefined;const rows=img.rows.map(row=>img.spec.headers.map(h=>row.values[h]??row.human[h]??row.formulas[h]??''));return {getWorksheet:()=>sheets[img.spec.sheet],getHeaderRowRange:()=>({getValues:()=>[img.spec.headers],getRowIndex:()=>img.spec.row,getColumnIndex:()=>img.spec.column}),getShowTotals:()=>false,getRowCount:()=>rows.length,getRangeBetweenHeaderAndTotal:()=>makeRange(img.spec,rows),getRange:()=>({getRowIndex:()=>img.spec.row,getRowCount:()=>rows.length+1})};}},footer};
}
test('read-only bootstrap exports exact known IDs and machine hashes without inferring groups',()=>{const {book}=bootstrapBook();const result=JSON.parse(bootContext.bootstrap(book,JSON.stringify({mode:'inspect',workbookKey:'test',expectedSourceSha256:'',footerAddress:'A30:X33',expectedFooter:[],dailyRows:[]})));assert.equal(result.groupingMapVerified,false);assert.equal(result.seed[0].rows[0].key,'A01');assert.equal(result.seed[1].rows[0].key,'existing-occurrence');assert.equal(result.seed[2].rows[0].key,'existing-mail');assert.match(result.seed[0].rows[0].machineSha256,/^[a-f0-9]{64}$/);});
test('bootstrap refuses a stale reviewed source before changing any native cell',()=>{const {book,footer}=bootstrapBook();assert.throws(()=>bootContext.bootstrap(book,JSON.stringify({mode:'initialize',workbookKey:'test',expectedSourceSha256:'0'.repeat(64),footerAddress:'A30:X33',expectedFooter:footer,dailyRows:[]})),/changed since/);});

const {convertBootstrapSeed}=require('./convert-bootstrap-seed.cjs');
function exportedSeed(){const groups=[['actions',change(0,'A01')],['instances',change(1,'raw-occurrence',{Instance:'EV-003'})],['emails',change(2,'raw-mail',{Email:'EM-005','Linked instance':'EV-003'})],['dailyRows',change(3,'daily-reference',{'Reporting day':'Reviewed reporting window'})]];const sourceSha256='a'.repeat(64);return {snapshot:{initialized:true,revision:0,workbookKey:'test',sourceSha256,counts:{actions:1,instances:1,emails:1,dailyRows:1},seed:groups.map(([group,row])=>({group,rows:[{key:row.key,values:row.values,links:row.links,machineSha256:api.rowDigest(row)}]}))},review:{schemaVersion:1,reviewed:true,workbookKey:'test',mailbox:'synthetic@example.test',sourceSha256,actionMappings:{'reviewed-signature':'A01'}}};}
test('offline seed conversion preserves raw IDs, existing display IDs, exact mail joins and daily period',()=>{const {snapshot,review}=exportedSeed(),result=convertBootstrapSeed(snapshot,review);assert.equal(result.settings.enabled,false);assert.equal(result.settings.seedVerified,false);assert.deepEqual(result.seedMetadata.counters,{action:1,instance:3,email:5});assert.deepEqual(result.seedMetadata.counts,{actions:1,instances:1,emails:1,dailyRows:1});assert.equal(result.rowDocuments.find(row=>row.data.group==='emails').data.value.eventRef,'raw-occurrence');assert.equal(result.rowDocuments.find(row=>row.data.group==='dailyRows').data.value.values['Reporting day'],'Reviewed reporting window');assert.equal(result.seedMetadata.actionMappings['reviewed-signature'],'A01');});
test('offline seed conversion cannot invent missing group mappings or ignore changed native hashes',()=>{const {snapshot,review}=exportedSeed();review.actionMappings.bad='A99';assert.throws(()=>convertBootstrapSeed(snapshot,review),/missing Action/);delete review.actionMappings.bad;snapshot.seed[0].rows[0].values.Problem='altered';assert.throws(()=>convertBootstrapSeed(snapshot,review),/hash mismatch/);});
test('real backend normalizer and sealed bridge payload match native writer schema and hash contract',()=>{const {normalizeIssueTracker}=require('../../functions/issue-tracker-normalize'),{sealBatch}=require('../../functions/issue-tracker-bridge-model');const id='a'.repeat(64),normalized=normalizeIssueTracker({occurrences:[{id,issueId:'b'.repeat(64),message:'Synthetic unknown failure',operation:'synthetic-test',receivedAtMillis:1790892000000}],outbox:[{id,type:'incident',issueId:'b'.repeat(64),status:'pending'}]});const batch=sealBatch({batchId:'synthetic-integration',workbookKey:'test',expectedRevision:0,generatedAt:'2026-10-01T22:00:00.000Z',changes:normalized.changes});api.validateEnvelope(batch);const images=api.SPECS.map((spec,i)=>image(i,[])),plans=images.map(img=>api.planTable(img,normalized.changes[img.spec.group],false));api.validateReferences(images,plans);assert.equal(plans[1].updates[0].change.key,id);});
