"""Offline expression/structure tests. Actual tenant save + read remain gates."""
import json
from pathlib import Path
import re
import tempfile
import unittest
import zipfile

import build_mail_read_flow as m


class Expressions:
    """Evaluate only the WDL string/query subset actually generated by builder.

    Tests inspect/evaluate emitted expressions, not a second route implementation.
    This is an offline model, not a Microsoft runtime acceptance receipt.
    """
    def __init__(self, outputs, item=None):
        self.outputs, self.item = outputs, item

    def evaluate(self, expression):
        tokens = re.findall(r"'(?:''|[^'])*'|[A-Za-z_][A-Za-z_0-9]*|[0-9]+|\?\[|[(),\]]", expression.lstrip('@'))
        pos = 0

        def parse():
            nonlocal pos
            token = tokens[pos]; pos += 1
            if token.startswith("'"):
                value = token[1:-1].replace("''", "'")
            elif token.isdigit():
                value = int(token)
            elif token in ('true','false'):
                value = token == 'true'
            else:
                self_test = tokens[pos]; pos += 1
                assert self_test == '('
                args = []
                if tokens[pos] != ')':
                    while True:
                        args.append(parse())
                        if tokens[pos] != ',': break
                        pos += 1
                assert tokens[pos] == ')'; pos += 1
                ops = {'body':lambda k:self.outputs[k], 'outputs':lambda k:self.outputs[k], 'item':lambda:self.item,
                    'first':lambda x:x[0], 'split':lambda s,d:s.split(d), 'replace':lambda s,a,b:s.replace(a,b),
                    'substring':lambda s,start,*length:s[start:start+length[0]] if length else s[start:],
                    'length':len, 'min':min, 'range':lambda start,count:list(range(start,start+count)),
                    'contains':lambda s,v:v in s, 'not':lambda x:not x, 'equals':lambda a,b:a==b,
                    'greater':lambda a,b:a>b, 'lessOrEquals':lambda a,b:a<=b, 'take':lambda s,n:s[:n],
                    'and':lambda *a:all(a), 'or':lambda *a:any(a)}
                value = ops[token](*args)
            if pos < len(tokens) and tokens[pos] == '?[':
                pos += 1; key=parse(); assert tokens[pos] == ']'; pos += 1; value=value.get(key)
            return value

        result = parse(); assert pos == len(tokens)
        return result


def permitted(url, request_id='11111111-2222-4333-8444-555555555555'):
    d=m.definition(); values={'Validate_schema':{'schemaVersion':1,'requestId':request_id,'url':url}}
    if len(request_id)!=36 or len(url)>8192 or len(url)<len(m.BASE): return False
    for name, a in d['actions'].items():
        if a['type']=='Compose': values[name]=Expressions(values).evaluate(a['inputs'])
        if a['type']=='Query':
            items=Expressions(values).evaluate(a['inputs']['from'])
            values[name]=[i for i in items if Expressions(values,i).evaluate(a['inputs']['where'])]
        if a['type']=='If': return Expressions(values).evaluate(a['expression'])
    raise AssertionError('route guard absent')


def all_actions(actions):
    for name, a in actions.items():
        yield name,a
        if 'actions' in a: yield from all_actions(a['actions'])
        if 'else' in a: yield from all_actions(a['else']['actions'])


class MailReadFlowTests(unittest.TestCase):
    def test_generated_expressions_allow_only_fixed_route_and_preserve_opaque_query(self):
        for base in [m.BASE,m.BASE.replace('@','%40')]:
            for suffix in ['', '?$skiptoken=%2F..%252F%23%40&$top=1', '/A_B-c%2BD%3d?$select=body,internetMessageHeaders']:
                with self.subTest(suffix=suffix): self.assertTrue(permitted(base+suffix))
        inputs=m.definition()['actions']['Allow_only_Dylan_message_GET']['actions']['Read_Dylan_messages']['inputs']
        self.assertEqual(inputs['parameters']['Uri'],"@body('Validate_schema')?['url']")

    def test_actual_expressions_refuse_mailbox_origin_and_encoding_escapes(self):
        bad=[m.BASE.replace('dylank',name) for name in ['nolanj','taiyow','alerts']]
        bad += [m.BASE.replace('/users/dylank@posetek.net','/me'),m.BASE.replace('https:','http:'),m.BASE.replace('graph.microsoft.com','graph.microsoft.com:443'),
            m.BASE.replace('graph.microsoft.com','user@graph.microsoft.com'),m.BASE.replace('/v1.0/','/beta/'),m.BASE.replace('https://','HTTPS://'),
            m.BASE+'#fragment',m.BASE+'\\escaped',m.BASE+'/../messages',m.BASE+'/%2e%2e',m.BASE+'/%2F',m.BASE+'/%252F',m.BASE+'/one/two',
            m.BASE+'/one%40two',m.BASE+'/one%3Ftwo',m.BASE+'/',m.BASE+'?x=raw space',m.BASE+'?x=\n',m.BASE+'?x=é',m.BASE+'?x=<bad>',
            m.BASE+'/'+m.BASE+'/id']
        for url in bad:
            with self.subTest(url=url): self.assertFalse(permitted(url))
        for c in [chr(n) for n in range(33)]+['\\','#']:
            self.assertFalse(permitted(m.BASE+'?x='+c))

    def test_request_schema_and_exact_request_id_shape(self):
        schema=m.definition()['actions']['Validate_schema']['inputs']['schema']
        self.assertFalse(schema['additionalProperties']);self.assertEqual(set(schema['required']),{'url','requestId','schemaVersion'})
        self.assertEqual(schema['properties']['schemaVersion']['enum'],[1]);self.assertNotIn('pattern',json.dumps(schema))
        for request_id in ['0'*36,'11111111-2222-4333-8444-55555555555g','111111112222-4333-8444-555555555555-','short']:
            self.assertFalse(permitted(m.BASE,request_id))

    def test_fixed_get_secure_io_exact_principal_no_trigger_concurrency_or_async_response(self):
        d=m.definition();trigger=d['triggers']['manual']
        self.assertEqual(trigger['inputs']['triggerAllowedUsers'],m.CALLER)
        self.assertEqual(trigger['inputs']['triggerAuthenticationType'],'User')
        self.assertNotIn('concurrency',trigger['runtimeConfiguration'])
        self.assertEqual(trigger['runtimeConfiguration'],m.SECURE)
        connector=[]
        for _,a in all_actions(d['actions']):
            if a['type']=='If':
                self.assertNotIn('runtimeConfiguration',a)
                self.assertEqual(a['expression'],"@equals(outputs('Route_is_allowed'),true)")
            else:
                expected=m.SECURE_INPUTS if a['type'] in ('ParseJson','Compose','Response') else m.SECURE
                self.assertEqual(a['runtimeConfiguration'],expected)
            self.assertIn(a['type'],['ParseJson','Compose','Query','If','OpenApiConnection','Response'])
            self.assertNotIn('operationOptions',a)
            if a['type']=='OpenApiConnection': connector.append(a)
        self.assertEqual(len(connector),1)
        inputs=connector[0]['inputs'];self.assertEqual(inputs['host']['operationId'],'HttpRequest')
        self.assertEqual(inputs['host']['apiId'],m.API);self.assertEqual(inputs['retryPolicy'],{'type':'none'})
        self.assertEqual(set(inputs['parameters']),{'Uri','Method','CustomHeader1'})
        self.assertEqual(inputs['parameters']['Method'],'GET')
        self.assertEqual(inputs['parameters']['CustomHeader1'],'Prefer: IdType="ImmutableId", outlook.body-content-type="html"')
        guard=d['actions']['Route_is_allowed']
        self.assertEqual(guard['runtimeConfiguration'],m.SECURE_INPUTS)
        self.assertIn("outputs('Message_path')",guard['inputs'])
        self.assertEqual(d['actions']['Allow_only_Dylan_message_GET']['runAfter'],{'Route_is_allowed':['Succeeded']})

    def test_response_requires_connector_success_and_preserves_original_json_with_bounded_errors(self):
        a=m.definition()['actions']['Allow_only_Dylan_message_GET']['actions']
        response=a['Return_complete_read'];self.assertEqual(response['runAfter'],{'Read_Dylan_messages':['Succeeded']})
        self.assertEqual(response['inputs']['statusCode'],200)
        self.assertEqual(response['inputs']['body'],{'schemaVersion':1,'requestId':"@body('Validate_schema')?['requestId']",'mailbox':m.MAILBOX,
            'graphStatus':"@outputs('Read_Dylan_messages')?['statusCode']",'data':"@body('Read_Dylan_messages')"})
        self.assertEqual(a['Return_read_failure']['inputs']['body'],{'error':'mail_read_failed'})

    def test_package_is_new_private_stopped_and_connection_configuration_cannot_change_caller(self):
        with tempfile.TemporaryDirectory(dir=m.ROOT/'.netlify') as private:
            p=Path(private);cfg=p/'config.json';connection='shared-office365-11111111-2222-4333-8444-555555555555'
            cfg.write_text(json.dumps({'outlookConnectionName':connection}));out=p/'read-proxy.zip'
            result=m.build(out,cfg);self.assertTrue(result['configured']);self.assertFalse(result['imported'])
            with zipfile.ZipFile(out) as z:
                self.assertEqual(len(z.namelist()),5)
                doc=json.loads(z.read(next(n for n in z.namelist() if n.endswith('/definition.json'))))
                self.assertEqual(doc['properties']['state'],'Stopped');self.assertEqual(doc['properties']['definition'],m.definition())
                self.assertEqual(doc['properties']['connectionReferences']['shared_office365']['connectionName'],connection)
                manifest=json.loads(z.read('manifest.json'))
                self.assertEqual(manifest['resources'][doc['name']]['creationType'],'New')
            with self.assertRaises(ValueError):m.build(out,cfg)
            cfg.write_text(json.dumps({'callerObjectId':'different','outlookConnectionName':connection}))
            with self.assertRaises(ValueError):m.build(p/'other.zip',cfg)
        with self.assertRaises(ValueError):m.build(m.ROOT/'not-private.zip')


if __name__=='__main__':unittest.main()
