import { useMemo } from "react";
import { Link } from "react-router-dom";
import { AboutNumbers, ActivityChart, BreakdownChart } from "./BreakdownChart";
import type { BreakdownSlice } from "./BreakdownChart";
import { ageLabel, clearPlayerFilters, divisionLabel, hasPlayerFilters } from "./lib/expandedQuery";
import type { ExpandedRequest } from "./lib/expandedQuery";
import { EXERCISES, FEATURE_LABELS, minuteText, platformSlices, shortDate, TESTING_LABELS, USAGE_LABELS, weeklySeries, WORKOUT_LABELS, workoutDurationText, workoutOutcomeSlices } from "./lib/expanded";
import type { CountGroup, ExpandedInsights, ExpandedPlayer } from "./lib/expanded";
import { drillLabel } from "./lib/insights";
import PerformanceProgress from "./PerformanceProgress";

const groups = (rows: CountGroup[], labels: Record<string, string> | ((key: string) => string)): BreakdownSlice[] => rows.map(row => ({ key: row.key, value: row.count, label: typeof labels === "function" ? labels(row.key) : labels[row.key] || row.key }));
const amount = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 1 });
function Sparkline({ values, label }: { values: number[]; label: string }) {
  const width = 104, height = 28, max = Math.max(...values, 1), step = values.length > 1 ? width / (values.length - 1) : width;
  const points = values.map((value, index) => `${index * step},${height - value / max * (height - 3) - 1}`).join(" ");
  return <svg className="insights-sparkline" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label} preserveAspectRatio="none"><polyline points={points} /></svg>;
}
function Tile({ label, value, note, trend, trendLabel }: { label: string; value: string | number; note?: string; trend?: number[]; trendLabel?: string }) { return <div className="insights-tile"><span>{label}</span><div className="insights-tile-value"><strong>{typeof value === "number" ? amount(value) : value}</strong>{trend?.length ? <Sparkline values={trend} label={trendLabel || `${label} daily trend`} /> : null}</div>{note && <em>{note}</em>}</div>; }
function Status({ value, dateUnknown = false }: { value: string; dateUnknown?: boolean }) { return <><span className={`insights-status ${value === "fullyTested" ? "full" : value === "partiallyTested" ? "partial" : ""}`}>{TESTING_LABELS[value] || value}</span>{dateUnknown && <span className="insights-subtle">Date unknown · needs review</span>}</>; }

export function PlayerResultsTable({ data, view, page, busy, onPrevious, onNext, playerLink }: {
  data: ExpandedInsights; view: ExpandedRequest["view"]; page: number; busy?: boolean; onPrevious: () => void; onNext: () => void; playerLink: (player: ExpandedPlayer) => string;
}) {
  const start = page * data.pagination.pageSize + (data.players.length ? 1 : 0), end = page * data.pagination.pageSize + data.players.length;
  return <section className="insights-card" aria-labelledby="insights-players-heading">
    <div className="insights-section-title"><h2 id="insights-players-heading">Players</h2><span>{data.pagination.total.toLocaleString()} matching players</span></div>
    {data.players.length ? <div className="insights-table-wrap"><table className="insights-table"><caption className="insights-sr-only">Players matching the current filters</caption>
      <thead><tr><th scope="col">Player</th><th scope="col">Team</th>{view === "overview" && <><th scope="col">Division · age</th><th scope="col">Testing</th><th scope="col">Workouts completed</th><th scope="col">Estimated active use</th></>}
        {view === "testing" && <><th scope="col">Coverage</th>{EXERCISES.map(key => <th scope="col" key={key}>{drillLabel(key)}</th>)}<th scope="col">Qualifying results</th><th scope="col">Distinct recorded attempts</th></>}
        {view === "workouts" && <><th scope="col">Status</th><th scope="col">Started</th><th scope="col">Completed</th><th scope="col">Timer duration</th><th scope="col">Estimated duration</th></>}
        {view === "usage" && <><th scope="col">Usage</th><th scope="col">Active days</th><th scope="col">Estimated active use</th><th scope="col">Website</th><th scope="col">iOS app</th></>}
      </tr></thead><tbody>{data.players.map(player => <tr key={player.id}>
        <th scope="row"><Link to={playerLink(player)}>{player.firstName} {player.lastName}</Link><span className="insights-subtle">{player.organizationName}</span></th><td>{player.teamName || "Unassigned"}</td>
        {view === "overview" && <><td>{divisionLabel(player.division)} · {player.age === null ? "Unknown" : player.age}</td><td><Status value={player.testing.status} dateUnknown={player.testing.hasDateUnknownAttempts} /><span className="insights-subtle">{player.testing.exercisesComplete}/6 exercises</span></td><td>{player.workouts.completed}</td><td>{minuteText(player.usage.activeMinutes, player.usage.collected)}</td></>}
        {view === "testing" && <><td><Status value={player.testing.status} dateUnknown={player.testing.hasDateUnknownAttempts} /><span className="insights-subtle">{player.testing.exercisesComplete}/6 exercises</span></td>{EXERCISES.map(key => <td key={key}>{player.testing.exerciseKeys?.includes(key) ? <span className="insights-check">✓<span className="insights-sr-only"> Qualified</span></span> : <span className="insights-subtle">No qualified result</span>}</td>)}<td>{player.testing.qualifyingTests}</td><td>{player.testing.distinctAttempts}</td></>}
        {view === "workouts" && <><td>{WORKOUT_LABELS[player.workouts.status] || player.workouts.status}</td><td>{player.workouts.started}</td><td>{player.workouts.completed}</td><td>{workoutDurationText(player.workouts.timerMinutes, player.workouts.timerRecords)}{player.workouts.timerRecords !== undefined && <span className="insights-subtle">{player.workouts.timerRecords}/{player.workouts.outcomeEvents} logs with timers</span>}</td><td>{workoutDurationText(player.workouts.estimatedMinutes, player.workouts.estimatedRecords)}{player.workouts.estimatedRecords !== undefined && <span className="insights-subtle">{player.workouts.estimatedRecords}/{player.workouts.outcomeEvents} logs with estimates</span>}</td></>}
        {view === "usage" && <><td>{USAGE_LABELS[player.usage.status] || player.usage.status}</td><td>{player.usage.collected ? player.usage.activeDays : "Not collected"}</td><td>{minuteText(player.usage.activeMinutes, player.usage.collected)}</td><td>{minuteText(player.usage.webMinutes, player.usage.webCollected)}</td><td>{minuteText(player.usage.iosMinutes, player.usage.iosCollected)}</td></>}
      </tr>)}</tbody></table></div> : <p>No players match these filters.</p>}
    <div className="insights-pagination"><span>{data.players.length ? `${start}–${end} of ${data.pagination.total.toLocaleString()}` : "0 players"} · totals above cover every matching player</span><div><button className="quiet-button" type="button" disabled={page === 0 || busy} onClick={onPrevious}>Previous</button><button className="quiet-button" type="button" disabled={!data.pagination.nextCursor || busy} onClick={onNext}>Next</button></div></div>
  </section>;
}

export default function ExpandedReport({ data, request, onChange, adminOverview = false, hidePlayerTable = false, page = 0, onPrevious, onNext, playerLink }: {
  data: ExpandedInsights; request: ExpandedRequest; onChange: (patch: Partial<ExpandedRequest>) => void; adminOverview?: boolean; hidePlayerTable?: boolean; page?: number; onPrevious: () => void; onNext: () => void; playerLink: (player: ExpandedPlayer) => string;
}) {
  const { testing, workouts, usage, roster } = data, view = request.view;
  const count = (key: string) => testing.statuses.find(row => row.key === key)?.count || 0;
  const denominator = `${roster.filtered.toLocaleString()} matching players. Select a category to filter the roster.`;
  const testSlices = useMemo(() => groups(testing.statuses, TESTING_LABELS), [testing.statuses]);
  const workoutSlices = useMemo(() => groups(workouts.statuses, WORKOUT_LABELS), [workouts.statuses]);
  const outcomeSlices = useMemo(() => workoutOutcomeSlices(workouts), [workouts]);
  const outcomeCount = workouts.outcomeEvents ?? outcomeSlices.reduce((sum, row) => sum + row.value, 0);
  const durationCoverage = (records: number | undefined, source: string) => records === undefined ? "Coverage unavailable; refresh report" : `${records}/${outcomeCount} logs with ${source}`;
  const usageSlices = useMemo(() => groups(usage.statuses, USAGE_LABELS), [usage.statuses]);
  const divisions = useMemo(() => groups(data.demographics.division, divisionLabel), [data.demographics.division]);
  const ages = useMemo(() => groups(data.demographics.ageBand, ageLabel), [data.demographics.ageBand]);
  const period = `${shortDate(data.period.startDate)}–${shortDate(data.period.endDate)}`;
  const testingScope = data.testingMode === "cumulative" ? `Cumulative through ${data.period.endDate}` : `In selected period: ${period}`;
  const testWeeks = useMemo(() => weeklySeries(testing.days, ["distinctAttempts", "qualifyingTests"], data.period.startDate, data.period.endDate), [testing.days, data.period]);
  const workoutWeeks = useMemo(() => weeklySeries(workouts.days, ["started", "completed"], data.period.startDate, data.period.endDate), [workouts.days, data.period]);
  const usageWeeks = useMemo(() => weeklySeries(usage.days, ["webMinutes", "iosMinutes"], data.period.startDate, data.period.endDate, [usage.webCollectedPlayers > 0, usage.iosCollectedPlayers > 0]), [usage, data.period]);
  const filterLabels = { division: divisionLabel(request.division), ageBand: ageLabel(request.ageBand), testingStatus: TESTING_LABELS[request.testingStatus], workoutStatus: WORKOUT_LABELS[request.workoutStatus], usageStatus: USAGE_LABELS[request.usageStatus], usagePlatform: ({ web: "Website only", ios: "iOS only", both: "Both at once" } as Record<string,string>)[request.usagePlatform], usageFeature: FEATURE_LABELS[request.usageFeature] || request.usageFeature, teamAssignment: request.teamAssignment === "unassigned" ? "Unassigned players" : "Assigned players" };
  const adminQuery = new URLSearchParams();
  if (request.orgId) adminQuery.set("orgId", request.orgId);
  if (request.teamId) adminQuery.set("teamId", request.teamId);
  const adminHref = (path: string) => `${path}${adminQuery.size ? `?${adminQuery}` : ""}`;
  const teamSlices = data.scopeBreakdown.teams.map(row => ({ key: `${row.organizationId}:${row.id || "unassigned"}`, label: data.scope.kind === "global" ? `${row.name} · ${data.choices.organizations.find(org => org.id === row.organizationId)?.name || "Organization"}` : row.name, value: row.count }));
  const selectTeam = (key: string) => { const row = data.scopeBreakdown.teams.find(team => `${team.organizationId}:${team.id || "unassigned"}` === key); if (row) onChange({ orgId: row.organizationId, teamId: row.id || undefined, coachId: undefined, teamAssignment: row.id ? "" : "unassigned" }); };
  return <>
    <div className="insights-toolbar"><p className="insights-note">{roster.filtered.toLocaleString()} of {roster.included.toLocaleString()} included players · current roster{data.scope.assignedTeamsOnly ? " · assigned teams only" : ""}</p>{hasPlayerFilters(request) && <button className="insights-text-button" type="button" onClick={() => onChange(clearPlayerFilters())}>Clear all filters</button>}</div>
    {hasPlayerFilters(request) && <div className="insights-filter-chips" aria-label="Active player filters">{(Object.keys(filterLabels) as (keyof typeof filterLabels)[]).filter(key => request[key]).map(key => <button type="button" key={key} onClick={() => onChange({ [key]: "" })}>{filterLabels[key]} <span aria-hidden="true">×</span><span className="insights-sr-only"> Remove filter</span></button>)}</div>}
    <section className="insights-tiles" aria-label={`${view} summary`}>
      {view === "overview" && <><Tile label="Players" value={roster.filtered} note="Current filtered roster" trend={testing.days.map(row => row.recordedDocuments)} trendLabel="Daily recording activity" /><Tile label="Fully tested" value={count("fullyTested")} note={testingScope} trend={testing.days.map(row => row.qualifyingTests)} trendLabel="Daily qualifying results" /><Tile label="Workouts completed" value={workouts.completed} note="In selected period" trend={workouts.days.map(row => row.completed)} trendLabel="Daily completed workouts" /><Tile label="Estimated active use" value={minuteText(usage.activeMinutes, usage.collectedPlayers > 0)} note={`${usage.collectedPlayers}/${roster.filtered} players with collection`} trend={usage.days.map(row => row.activeMinutes || 0)} trendLabel="Daily estimated active use" /></>}
      {view === "testing" && <><Tile label="Fully tested" value={count("fullyTested")} note="All six exercises" /><Tile label="Partially tested" value={count("partiallyTested")} note="One to five exercises" /><Tile label="Qualifying results" value={testing.qualifyingTests} note={testingScope} /><Tile label="Distinct recorded attempts" value={testing.distinctAttempts} note="Recorded documents; duplicates counted once" /></>}
      {view === "workouts" && <><Tile label="Workouts completed" value={workouts.completed} note="Completed as logged" /><Tile label="Workouts started" value={workouts.started} note="Started in selected period" /><Tile label="Timer duration" value={workoutDurationText(workouts.timerMinutes, workouts.timerRecords)} note={durationCoverage(workouts.timerRecords, "timers")} /><Tile label="Estimated duration" value={workoutDurationText(workouts.estimatedMinutes, workouts.estimatedRecords)} note={durationCoverage(workouts.estimatedRecords, "estimates")} /></>}
      {view === "usage" && <><Tile label="Active players" value={usage.collectedPlayers ? usage.activePlayers : "Not collected"} note="At least one active local day" /><Tile label="Returning players" value={usage.collectedPlayers ? usage.returningPlayers : "Not collected"} note="Active on two or more days" /><Tile label="Estimated active use" value={minuteText(usage.activeMinutes, usage.collectedPlayers > 0)} note="Overlapping time counted once" /><Tile label="Collection coverage" value={`${usage.collectedPlayers}/${roster.filtered}`} note={`${usage.notCollectedPlayers} not collected`} /></>}
    </section>
    {(view === "overview" || view === "testing") && <AboutNumbers><p>{testingScope}. One completed rep with a required valid primary result qualifies each exercise. Missing or unresolved results do not qualify.</p></AboutNumbers>}
    {view === "overview" && adminOverview && <div className="admin-overview-panels">
      <section className="insights-card admin-attention"><div className="insights-section-title"><h2>Needs attention</h2><span>Current scope</span></div><ul>
        <li><Link to={adminHref("/admin/analysis")}><span>{testing.needsReview.toLocaleString()} reps need review</span><span aria-hidden="true">→</span></Link></li>
        <li><Link to={adminHref("/admin/analysis")}><span>{(testing.unmatchedFailureReports || 0).toLocaleString()} unmatched failure reports</span><span aria-hidden="true">→</span></Link></li>
        <li><Link to={adminHref("/admin/accounts")}><span>{count("noRecordedTests").toLocaleString()} players not tested</span><span aria-hidden="true">→</span></Link></li>
      </ul></section>
      <BreakdownChart title="Testing coverage" slices={testSlices} selected={request.testingStatus} onSelect={testingStatus => onChange({ testingStatus })} note={denominator} />
      {data.scope.kind !== "team" && data.scope.kind !== "coachRoster" && <BreakdownChart title="Players by team" slices={teamSlices} onSelect={selectTeam} note="Select a team to open its scope. Unassigned players stay within their organization." />}
    </div>}
    {view === "overview" && data.participation && <section className="insights-card"><div className="insights-section-title"><h2>Recent participation</h2><span>{data.period.startDate}–{data.period.endDate}</span></div><div className="insights-drills"><span>Testing or workouts <strong>{data.participation.anyPlayers}/{roster.filtered} players</strong></span><span>Recorded testing <strong>{data.participation.testingPlayers}</strong></span><span>Workout activity <strong>{data.participation.workoutPlayers}</strong></span></div><AboutNumbers><p>Players with dated testing recordings or workout starts/endings in the selected period. The combined count includes each player once; testing recordings may include unsuccessful attempts.</p></AboutNumbers></section>}
    <div className="insights-grid">
      {(view === "testing" || view === "overview" && !adminOverview) && <BreakdownChart title="Testing coverage" slices={testSlices} selected={request.testingStatus} onSelect={testingStatus => onChange({ testingStatus })} note={denominator} />}
      {view === "overview" && <><BreakdownChart title="Boys/Girls divisions" slices={divisions} selected={request.division} onSelect={division => onChange({ division })} note="Verified roster classification, not gender. Missing metadata is Unknown." /><BreakdownChart title="Current age" slices={ages} selected={request.ageBand} onSelect={ageBand => onChange({ ageBand })} note="Current valid birth date or recent recorded age. Missing or stale age is Unknown." /><BreakdownChart title="Player engagement" slices={usageSlices} selected={request.usageStatus} onSelect={usageStatus => onChange({ usageStatus })} note={denominator} /></>}
      {view === "testing" && <ActivityChart title="Players qualified by exercise" labels={testing.exercises.map(row => drillLabel(row.key))} series={[{ label: "Players qualified", values: testing.exercises.map(row => row.playersQualified) }]} unit="players" rowLabel="Exercise" note={`Each exercise uses ${roster.filtered} matching players as its denominator. A player can qualify in several exercises.`} />}
      {view === "workouts" && <><BreakdownChart title="Player workout status" slices={workoutSlices} selected={request.workoutStatus} onSelect={workoutStatus => onChange({ workoutStatus })} note="One status per player: completed takes priority, then no ending record, ended early, abandoned, none. An open log does not mean the player is training now." /><BreakdownChart title="Workout outcomes" slices={outcomeSlices} unit="workouts" note={`${outcomeCount} distinct workout logs: ended in this period, or started in this period with no ending record. Every outcome stays visible, including different outcomes for the same player. Starts are counted separately; a workout can begin before this period.`} /><section className="insights-card"><h2>Work completed</h2><div className="insights-tiles"><Tile label="All prescribed sets recorded" value={workouts.knownPrescription === undefined ? workouts.allPrescribedSetsCompleted : `${workouts.allPrescribedSetsCompleted}/${workouts.knownPrescription}`} note={workouts.knownPrescription === undefined ? "Prescription coverage unavailable" : `Of ${workouts.knownPrescription} logs with a known prescription`} /><Tile label="Unknown prescription" value={`${workouts.unknownPrescription}/${outcomeCount}`} note="Of all outcome logs; full completion cannot be assessed" /></div><div className="insights-drills"><span>Done blocks <strong>{workouts.doneBlocks}</strong></span><span>Partial blocks <strong>{workouts.partialBlocks}</strong></span><span>Skipped blocks <strong>{workouts.skippedBlocks}</strong></span><span>Sets recorded <strong>{workouts.setsCompleted}</strong></span></div><AboutNumbers><p>A completed workout log may still contain skipped or partial blocks. Prescription coverage: {workouts.knownPrescription === undefined ? "unavailable" : `${workouts.knownPrescription}/${outcomeCount} logs have a known prescription`}.</p></AboutNumbers></section></>}
      {view === "usage" && <><BreakdownChart title="Player engagement" slices={usageSlices} selected={request.usageStatus} onSelect={usageStatus => onChange({ usageStatus })} note="Returning means at least two active local days. No active use requires collection coverage; missing collection is separate." />{usage.collectedPlayers > 0 ? <BreakdownChart title="Active use by platform" slices={platformSlices(usage)} selected={request.usagePlatform} onSelect={usagePlatform => onChange({ usagePlatform })} unit="minutes" note="Website only, iOS only and overlap are mutually exclusive. Select a segment to see players with time in that category." /> : <section className="insights-card"><h2>Active use by platform</h2><div className="insights-uncollected"><strong>Not collected</strong><p>Usage starts when each platform sends measured activity. Earlier time cannot be reconstructed from testing records.</p></div></section>}</>}
    </div>
    {view === "overview" && !adminOverview && data.scope.kind !== "team" && data.scope.kind !== "coachRoster" && <div className="insights-grid">
      {data.scope.kind === "global" && <BreakdownChart title="Players by organization" slices={data.scopeBreakdown.organizations.map(row => ({ key: row.id, label: row.name, value: row.count }))} onSelect={orgId => { if (orgId) onChange({ orgId, teamId: undefined, coachId: undefined, teamAssignment: "" }); }} note="Select an organization to open its current roster." />}
      <BreakdownChart title="Players by team" slices={teamSlices} onSelect={selectTeam} note="Select a team to open its scope. Unassigned players stay within their organization." />
    </div>}
    {view === "testing" && <><ActivityChart title="Testing activity by week" labels={testWeeks.labels} series={[{ label: "Distinct recorded attempts", values: testWeeks.values[0] }, { label: "Qualifying results", values: testWeeks.values[1] }]} unit="results" note="This series always uses the selected period, even when coverage is cumulative." /><section className="insights-card"><div className="insights-section-title"><h2>Recording audit</h2><span>{amount(testing.recordedDocuments)} source documents</span></div><div className="insights-drills"><span>Duplicate documents <strong>{testing.duplicateDocuments}</strong></span><span>No result <strong>{testing.noResultDocuments}</strong></span><span>Needs review <strong>{testing.needsReview}</strong></span><span>Undated <strong>{testing.undatedDocuments}</strong></span><span>Future-dated <strong>{testing.futureDatedDocuments}</strong></span></div><AboutNumbers><p>Recording documents may include failed, duplicate or unresolved outputs. These issue counts are not additive successful-test totals.</p></AboutNumbers></section></>}
    {view === "workouts" && <><ActivityChart title="Workout activity by week" labels={workoutWeeks.labels} series={[{ label: "Started", values: workoutWeeks.values[0] }, { label: "Completed", values: workoutWeeks.values[1] }]} unit="workouts" /><AboutNumbers><p>Timer duration and estimated duration have different sources and are not added together. Duration coverage: {durationCoverage(workouts.timerRecords, "timers")}; {durationCoverage(workouts.estimatedRecords, "estimates")}; {workouts.unknownDuration}/{outcomeCount} logs have unknown duration. {workouts.duplicateLogs} duplicate logs were excluded. These figures describe training records, not website or app engagement.</p></AboutNumbers></>}
    {view === "usage" && <><AboutNumbers><p>Website: {usage.webCollectedPlayers ? `${usage.webCollectedPlayers} players with collection` : "Not collected"} · iOS app: {usage.iosCollectedPlayers ? `${usage.iosCollectedPlayers} players with collection` : "Not collected"}.{usage.collectionStartedAtMillis ? ` Collection began ${new Date(usage.collectionStartedAtMillis).toLocaleDateString("en-US", { timeZone: data.period.timeZone })}.` : " No collection is available in this period."}</p></AboutNumbers><ActivityChart title="Estimated active use by week" labels={usageWeeks.labels} series={[{ label: "Website", values: usageWeeks.values[0] }, { label: "iOS app", values: usageWeeks.values[1] }]} unit="minutes" note="Platform series can overlap. Total estimated active use counts simultaneous use once." />{Object.values(usage.featureMinutes).some(value => value > 0) && <div className="insights-grid"><BreakdownChart title="Estimated active use by feature" slices={Object.entries(usage.featureMinutes).map(([key, value]) => ({ key, label: FEATURE_LABELS[key] || key, value }))} selected={request.usageFeature} onSelect={usageFeature => onChange({ usageFeature })} unit="minutes" note="Each interval belongs to one feature. Select a feature to filter players with measured time there." /></div>}</>}
    {view === "testing" && <><section className="insights-card"><div className="insights-section-title"><h2>Failure reports</h2><span>Selected period · {data.period.startDate}–{data.period.endDate}</span></div><div className="insights-drills"><span>Total reports <strong>{testing.failureReports ?? "Unavailable"}</strong></span><span>Linked to recorded reps <strong>{testing.linkedFailureReports ?? "Unavailable"}</strong></span><span>Unmatched reports <strong>{testing.unmatchedFailureReports ?? "Unavailable"}</strong></span></div><AboutNumbers><p>Failure reports are separate diagnostic evidence and can overlap recorded attempts, including earlier failures before a later successful result. They are not added to recording documents, distinct recorded attempts or successful results. Standalone failure reports do not prove another saved recording.</p></AboutNumbers></section><PerformanceProgress data={data} /></>}
    {!hidePlayerTable && <PlayerResultsTable data={data} view={view} page={page} onPrevious={onPrevious} onNext={onNext} playerLink={playerLink} />}
    <AboutNumbers><p>Dates use {data.period.timeZone}; weeks begin Monday. Historical records follow current organization and team ownership. {roster.excluded > 0 ? `${roster.excluded} profiles are excluded by reporting metadata. ` : ""}Updated {new Date(data.generatedAtMillis).toLocaleString("en-US", { timeZone: data.period.timeZone })}. All totals use complete server summaries across the full filtered roster.</p></AboutNumbers>
  </>;
}
